### PR TITLE
removed some unnecessary files from the build

### PR DESCRIPTION
**Pull request by fvitt**

### CODE REVIEW

**Comment by cacraigucar** [comment]
Is this linked with changes to gmtb-scm and ccpp-framework or do these changes work without any other mods?

Does this run and can you see the value of CO being initialized and then halving?

**Comment by fvitt** [comment]
No changes to gmtb-scm.   It compiles and runs.  I did not check the CO
values.  We can talk more about it before you merge with your fork.

**Comment by cacraigucar** [comment]
Could you run "totalview gmtb-scm -a twpice" and then put in a breakpoint in chemistry_run.  Then you can look at CO and it should start out being 100, and the next time around decrease by half.  

If the CO has these values, then I'm eager to merge in your changes.

**Comment by fvitt** [comment]
I looked co in totalview -- initialized to 100 and halved each time
step.    I don't  understand the dimension of the co array -- size of 4.
Why not 2 dimensions (ncol,nvel)?

**Comment by cacraigucar** [comment]
This is simply because I was having an issue and mentioned it to Andrew.  He suggested that my problem might be that we are running a single column model and CO was 2D.  I decided to implement my own CO (hence my_co) and figured I might as well make it 1D in case that was the issue.  "my_co" is really just "my_made_up_variable" right now to get the init and run to work anyway I could.

**Comment by cacraigucar** [comment]
Did we need anymore discussion?  If not, I'm happy with the changes and I will merge them in.

**Comment by fvitt** [comment]
I think you can go ahead with the merge.  I would like to talk more about
what you implemented.

**Pull request merged**
